import assert from 'node:assert/strict';
import ExcelJS from 'exceljs';
import { readFile, parseCSV, checkZip } from '../lib/reconciliation/io.ts';
import { normalizeSource, compare } from '../lib/reconciliation/core.ts';
import { explainResult } from '../lib/reconciliation/assistant.ts';
import { interpretModelOutput } from '../lib/reconciliation/local-ai.ts';
import { demoFiles, demoMappings, demoScope } from '../lib/reconciliation/demo.ts';
const findings=[];
const scope={...demoScope,confirmed:true,coverageConfirmed:true};
const r=compare(normalizeSource(demoFiles[0],demoMappings[0],scope,'supplier'),normalizeSource(demoFiles[1],demoMappings[1],scope,'ledger'),scope);
const wrongRef=explainResult(r,'لماذا لم تطابق INV-001999؟');
assert.equal(wrongRef.kind,'transaction'); assert.ok(wrongRef.sourceIds.includes('supplier:0:2'));
findings.push({id:'A01',issue:'Nonexistent invoice question resolves to prefix invoice',question:'INV-001999',sourceIds:wrongRef.sourceIds});
const wb=new ExcelJS.Workbook(); const s=wb.addWorksheet('data');s.addRow(['date','reference','amount']);s.addRow(['2026-08-01','INV-100',1.234]);s.getCell('C2').numFmt='0.000';
const bytes=new Uint8Array(await wb.xlsx.writeBuffer()).buffer;
const parsed=await readFile('numeric.xlsx',bytes);
const map={...demoMappings[0],description:-1,currencyColumn:-1,amount:2,numberFormat:'comma',opening:'',closing:''};
const n=normalizeSource(parsed,map,{...scope,decimals:3},'supplier');
assert.equal(n.errors.length,0); assert.equal(n.transactions[0].amount,1234000);
const ledgerBook=new ExcelJS.Workbook();const ls=ledgerBook.addWorksheet('data');ls.addRow(['date','reference','amount']);ls.addRow(['2026-08-01','INV-100',1234]);ls.getCell('C2').numFmt='0.000';
const lfile=await readFile('ledger-numeric.xlsx',new Uint8Array(await ledgerBook.xlsx.writeBuffer()).buffer);
const falseMatch=compare(n,normalizeSource(lfile,map,{...scope,decimals:3},'ledger'),{...scope,decimals:3});
assert.equal(falseMatch.matches.length,1);
findings.push({id:'A02',falseAutoMatches:falseMatch.matches.length,issue:'XLSX native numeric value reparsed as locale-dependent text',actualExcelValue:1.234,actualMinorUnits:1234,engineMinorUnits:n.transactions[0].amount});
const p=interpretModelOutput(r,JSON.stringify({intent:'transaction',transactionId:'supplier:0:3'}));
assert.equal(p.kind,'transaction');
findings.push({id:'A03',issue:'Model routing validates ID existence, not association to user question',acceptedIds:p.sourceIds});
const tampered=bytes.slice(0);const dv=new DataView(tampered);let edits=0;for(let i=0;i<dv.byteLength-46;i++) if(dv.getUint32(i,true)===0x02014b50){dv.setUint32(i+24,1,true);edits++;}
checkZip(tampered);assert.ok(edits>0);
findings.push({id:'A04',issue:'ZIP precheck accepts falsified uncompressed lengths',modifiedEntries:edits,note:'Proves metadata trust only; not a memory exhaustion exploit'});
const wb2=new ExcelJS.Workbook();const s2=wb2.addWorksheet('data');s2.addRow(['date','reference','amount']);s2.addRow(['2026-08-01','INV-200',12.345]);s2.getCell('C2').numFmt='0.00';
const f2=await readFile('display.xlsx',new Uint8Array(await wb2.xlsx.writeBuffer()).buffer);
findings.push({id:'A05',issue:'Number formatting discarded on amount cells',displayFormat:'0.00',storedValue:12.345,parsed:f2.sheets[0].rows[1][2],note:'Here strict money parser rejects excess decimals; format evidence is lost'});
console.log(JSON.stringify(findings,null,2));
