import test from 'node:test';
import assert from 'node:assert/strict';
import ExcelJS from 'exceljs';
import { compare, normalizeSource } from '../lib/reconciliation/core.ts';
import { readFile, exportWorkbook } from '../lib/reconciliation/io.ts';
import { saveSession, restoreSession } from '../lib/reconciliation/session.ts';
import { explainResult } from '../lib/reconciliation/assistant.ts';
import type {
  Comparison,
  ReconciliationCase,
} from '../lib/reconciliation/types.ts';
import {
  loadPublicSyntheticNative,
  nativeHeaders,
} from './helpers/public-synthetic-native.ts';

// Always runs under tests/*.test.ts, with no private-file availability gate.
// Expected case arithmetic below is hand-authored, not generated by the engine.
const samples = Promise.all(
  ['xlsx', 'pdf'].map((extension) =>
    loadPublicSyntheticNative(extension as 'xlsx' | 'pdf'),
  ),
);
const members = (c: ReconciliationCase) => [
  ...c.supplierMembers,
  ...c.ledgerMembers,
];
function requiredCase(
  result: Comparison,
  classification: ReconciliationCase['classification'],
) {
  const cases = result.cases.filter((c) => c.classification === classification);
  assert.equal(cases.length, 1, classification);
  return cases[0];
}
function conserved(result: Comparison) {
  const expected = [
    ...result.supplier.transactions,
    ...result.ledger.transactions,
  ]
    .map((t) => t.id)
    .sort();
  const assigned = result.cases
    .flatMap((c) => members(c).map((t) => t.id))
    .sort();
  assert.equal(assigned.length, 13);
  assert.equal(new Set(assigned).size, 13);
  assert.deepEqual(assigned, expected);
  assert.deepEqual(
    result.cases.flatMap((c) => c.sourceTrace.map((t) => t.sourceRowId)).sort(),
    expected,
  );
}
const businessCases = (result: Comparison) =>
  result.cases.map((c) => ({
    classification: c.classification,
    status: c.status,
    supplier: c.supplierMembers.map((t) => [t.date, t.reference, t.amount]),
    ledger: c.ledgerMembers.map((t) => [t.date, t.reference, t.amount]),
    supplierTotal: c.supplierTotal,
    ledgerTotal: c.ledgerTotal,
    variance: c.variance,
    bridgeEffect: c.bridgeEffect,
  }));

void test('public synthetic native XLSX/PDF preserve physical date, reference, amount and source-row roles', async () => {
  for (const {
    extension,
    files,
    selections,
    formats,
    proofs,
    mappings,
    result,
  } of await samples) {
    assert.deepEqual(
      selections.map((s) => s.kind),
      ['unique-table', 'unique-table'],
    );
    assert.deepEqual(
      formats.map((f) => [f.dateFormat.status, f.numberFormat.status]),
      [
        ['proven', 'proven'],
        ['proven', 'proven'],
      ],
    );
    assert.deepEqual(
      proofs.map((p) => [p!.multiplier, p!.balanceColumn, p!.checkedRows]),
      [
        [1, 11, 6],
        [-1, 11, 7],
      ],
    );
    files.forEach((file, side) => {
      const sheet = file.sheets[0];
      assert.deepEqual(
        sheet.rows[2],
        nativeHeaders(side === 0 ? 'supplier' : 'ledger'),
      );
      assert.equal(
        mappings[side].date,
        0,
        'Posting/transaction date must outrank the other date',
      );
      assert.equal(
        mappings[side].reference,
        4,
        'Document number must not become the local AP voucher',
      );
      assert.equal(mappings[side].debit, 9);
      assert.equal(
        mappings[side].credit,
        10,
        'Running balance must not become a movement',
      );
      if (extension === 'xlsx') {
        assert.deepEqual(sheet.numericCells?.['5:11'], {
          value: side === 0 ? 0 : 219.47,
          format: '#,##0.00',
        });
      } else {
        assert.equal(file.pdf?.cuts.length, 11);
        assert.equal(sheet.rowIssues?.['3'], undefined);
        for (const t of side === 0
          ? result.supplier.transactions
          : result.ledger.transactions)
          assert.equal(t.sourcePage, 1);
      }
    });
    assert.deepEqual(
      result.supplier.transactions.map((t) => [t.row, t.date, t.amount]),
      [
        [5, '2034-02-03', 21947],
        [6, '2034-02-05', -1865],
        [7, '2034-02-09', 14329],
        [8, '2034-02-13', 8734],
        [9, '2034-02-17', -4683],
        [10, '2034-02-23', 2458],
      ],
    );
    assert.deepEqual(
      result.ledger.transactions.map((t) => [t.row, t.date, t.amount]),
      [
        [5, '2034-02-04', 21947],
        [6, '2034-02-06', -1865],
        [7, '2034-02-10', 6117],
        [8, '2034-02-10', 8212],
        [9, '2034-02-14', 8519],
        [10, '2034-02-18', -4683],
        [11, '2034-02-25', 1107],
      ],
    );
    for (const [side, source] of [result.supplier, result.ledger].entries()) {
      assert.deepEqual(source.errors, []);
      assert.deepEqual(
        source.excluded.map((e) => e.row),
        [1, 2, 3, 4, side === 0 ? 11 : 12],
      );
      assert.equal(
        source.balanceArithmeticStatus,
        'BALANCE_ARITHMETIC_VERIFIED',
      );
      assert.equal(source.periodStatus, 'PERIOD_DETECTED');
      assert.equal(source.coverageStatus, 'PERIOD_COVERAGE_UNCONFIRMED');
      assert.equal(source.metadata?.periodStart, '2034-02-01');
      assert.equal(source.metadata?.periodEnd, '2034-02-28');
    }
    assert.equal(
      result.balanceComparable,
      false,
      'Arithmetic does not approve period coverage',
    );
    conserved(result);
  }
});

void test('public synthetic case inventory and bridge equal hand-calculated expectations in both native formats', async () => {
  const [excel, pdf] = await samples;
  assert.deepEqual(businessCases(excel.result), businessCases(pdf.result));
  for (const { result } of [excel, pdf]) {
    assert.deepEqual(
      result.cases.map((c) => [
        c.classification,
        c.status,
        c.supplierTotal,
        c.ledgerTotal,
        c.variance,
        c.bridgeEffect,
      ]),
      [
        ['EXACT_1_TO_1', 'Matched', 21947, 21947, 0, 0],
        ['EXACT_1_TO_1', 'Matched', -1865, -1865, 0, 0],
        ['EXACT_1_TO_MANY', 'Matched', 14329, 14329, 0, 0],
        ['AMOUNT_VARIANCE', 'Needs Review', 8734, 8519, 215, -215],
        ['PAYMENT_CANDIDATE', 'Needs Review', -4683, -4683, 0, 0],
        ['SUPPLIER_ONLY', 'Unmatched', 2458, 0, 2458, -2458],
        ['LEDGER_ONLY', 'Unmatched', 0, 1107, -1107, 1107],
      ],
    );
    assert.deepEqual(result.caseCounts, {
      autoMatchedCases: 3,
      matchedSourceRows: 7,
      needsReviewCases: 2,
      needsReviewSourceRows: 4,
      unmatchedCases: 2,
      unmatchedSourceRows: 2,
      manualMatches: 0,
      rejectedCandidates: 0,
    });
    assert.deepEqual(
      [result.supplier.opening, result.supplier.closing, result.supplier.total],
      [6789, 47709, 40920],
    );
    assert.deepEqual(
      [result.ledger.opening, result.ledger.closing, result.ledger.total],
      [6789, 46143, 39354],
    );
    assert.deepEqual(result.bridge, {
      delta: 1566,
      openingAdjustment: 0,
      itemAdjustment: -1566,
      adjusted: 46143,
      residual: 0,
    });
    assert.equal(
      result.cases.reduce((sum, c) => sum + c.bridgeEffect, 0),
      -1566,
    );
    const group = requiredCase(result, 'EXACT_1_TO_MANY');
    assert.deepEqual(
      [group.supplierMembers.length, group.ledgerMembers.length],
      [1, 2],
    );
    assert.deepEqual(
      group.ledgerMembers.map((t) => [
        t.documentReference,
        t.voucherReference,
        t.poReference,
      ]),
      [
        ['SYN-NATIVE-83-GROUP', 'AP-SYN-NATIVE-83-G', 'PO-SYN-NATIVE-83-G'],
        ['SYN-NATIVE-83-GROUP', 'AP-SYN-NATIVE-83-G', 'PO-SYN-NATIVE-83-G'],
      ],
    );
    assert.equal(group.reviewRequired, false);
    const ids = new Set(members(group).map((t) => t.id));
    assert.equal(
      result.diagnostics.some(
        (d) =>
          d.code === 'DUPLICATE_REFERENCE' &&
          d.transactionIds.some((id) => ids.has(id)),
      ),
      false,
    );
    assert.equal(
      result.diagnostics.some((d) => d.code === 'BALANCE_UNVERIFIED'),
      false,
    );
    assert.ok(
      result.diagnostics.some((d) => d.code === 'PERIOD_COVERAGE_UNCONFIRMED'),
    );
  }
});

void test('public synthetic unreadable PO or conflicting group voucher cannot be erased into an automatic invoice group', async () => {
  for (const { files, mappings, result } of await samples) {
    for (const fault of ['unsafe-po', 'different-voucher'] as const) {
      const altered = structuredClone(files[1]);
      const row = requiredCase(result, 'EXACT_1_TO_MANY').ledgerMembers[0].row;
      const sheet = altered.sheets[0];
      if (fault === 'unsafe-po') {
        sheet.rows[row - 1][5] = 'PO-SYN-NATIVE-99';
        (sheet.cellIssues ??= {})[`${row}:6`] = [
          'Unreadable synthetic reference',
        ];
      } else sheet.rows[row - 1][3] = 'AP-SYN-NATIVE-99';
      const ledger = normalizeSource(
        altered,
        mappings[1],
        result.scope,
        'ledger',
      );
      assert.deepEqual(ledger.errors, []);
      const checked = compare(result.supplier, ledger, result.scope);
      assert.equal(
        checked.cases.some((c) => c.classification === 'EXACT_1_TO_MANY'),
        false,
        fault,
      );
      assert.equal(
        requiredCase(checked, 'AMBIGUOUS_CANDIDATE').status,
        'Needs Review',
        fault,
      );
      assert.equal(
        requiredCase(checked, 'PAYMENT_CANDIDATE').status,
        'Needs Review',
      );
      conserved(checked);
    }
  }
});

void test('public synthetic payment stays reviewed until an explicit decision, and explanations cite its exact rows', async () => {
  for (const { files, mappings, result } of await samples) {
    const payment = requiredCase(result, 'PAYMENT_CANDIDATE');
    assert.equal(payment.reviewRequired, true);
    assert.notEqual(
      payment.supplierMembers[0].primaryReference,
      payment.ledgerMembers[0].primaryReference,
    );
    assert.equal(
      payment.supplierMembers[0].receiptReference,
      'RCPT-SYN-NATIVE-83-Q',
    );
    assert.equal(
      payment.ledgerMembers[0].voucherReference,
      'PYM-SYN-NATIVE-83-R',
    );
    assert.deepEqual(payment.supplierMembers[0].paymentIdentityFields, [
      'receiptReference',
    ]);
    assert.deepEqual(
      payment.ledgerMembers[0].paymentIdentityFields,
      [],
      'Mixed PO/bank values are audit references, not explicit payment identity',
    );
    for (const reference of [
      'RCPT-SYN-NATIVE-83-Q',
      'BANK-SYN-NATIVE-83-Q',
      'PYM-SYN-NATIVE-83-R',
      'BANK-SYN-NATIVE-83-R',
    ]) {
      const answer = explainResult(result, `اشرح ${reference}`);
      assert.equal(answer.kind, 'transaction');
      assert.ok(answer.text.includes('PAYMENT_CANDIDATE'));
      assert.deepEqual(
        new Set(answer.sourceIds),
        new Set(payment.sourceTrace.map((t) => t.sourceRowId)),
      );
    }
    const accepted = compare(result.supplier, result.ledger, result.scope, [
      {
        supplierId: payment.supplierMembers[0].id,
        ledgerId: payment.ledgerMembers[0].id,
        note: 'Fictional reviewer approved the independently authored payment evidence',
      },
    ]);
    assert.equal(accepted.caseCounts.manualMatches, 1);
    assert.equal(accepted.caseCounts.autoMatchedCases, 3);
    const manual = accepted.cases.filter(
      (c) => c.matchingRule === 'MANUAL_REVIEW',
    );
    assert.equal(manual.length, 1);
    assert.equal(manual[0].status, 'Matched');
    assert.equal(manual[0].reviewerDecision, 'Accepted');
    assert.deepEqual(accepted.bridge, result.bridge);
    conserved(accepted);
    // An explicit contradictory bank identity cannot be overridden even by a
    // reviewer. Move the same literals into their dedicated identity column.
    const explicit = files.map((file, side) => {
      const changed = structuredClone(file);
      const row =
        side === 0
          ? payment.supplierMembers[0].row
          : payment.ledgerMembers[0].row;
      changed.sheets[0].rows[row - 1][7] = changed.sheets[0].rows[row - 1][5];
      return normalizeSource(
        changed,
        mappings[side],
        result.scope,
        side === 0 ? 'supplier' : 'ledger',
      );
    });
    assert.throws(
      () =>
        compare(explicit[0], explicit[1], result.scope, [
          {
            supplierId: payment.supplierMembers[0].id,
            ledgerId: payment.ledgerMembers[0].id,
            note: 'A reviewer cannot override explicit contradictory source identities',
          },
        ]),
      /تعارض صريح/,
    );
  }
});

void test('public synthetic audit workbook uses native cells, unique case sheets and formulas, original-byte session replay and rejection of altered exported arithmetic', async () => {
  for (const { extension, files, mappings, result } of await samples) {
    const review = { checked: false, name: '', notes: '' };
    const book = new ExcelJS.Workbook();
    await book.xlsx.load(await exportWorkbook(result, files, review));
    const visible = [
      'Summary',
      'Matches',
      'Needs Review',
      'Unmatched',
      'Reconciliation Bridge',
      'Review Sign-off',
    ];
    assert.deepEqual(
      book.worksheets.filter((s) => s.state === 'visible').map((s) => s.name),
      visible,
    );
    for (const sheet of book.worksheets.filter(
      (s) => !visible.includes(s.name),
    ))
      assert.equal(sheet.state, 'hidden');
    const ids: string[] = [];
    for (const [name, rows, amounts, dates] of [
      ['Matches', 4, 6, 6],
      ['Needs Review', 3, 6, 0],
      ['Unmatched', 3, 2, 2],
    ] as const) {
      const sheet = book.getWorksheet(name)!;
      assert.equal(sheet.rowCount, rows);
      assert.ok(sheet.autoFilter);
      let typedAmounts = 0,
        typedDates = 0;
      sheet.getRow(1).eachCell((header, column) => {
        const amount =
          /^(Supplier (Amount|Total)|Ledger (Amount|Total)|Variance|Amount)$/.test(
            header.text,
          );
        const date = /^(Supplier Date|Ledger Date|Date)$/.test(header.text);
        for (let row = 2; row <= sheet.rowCount; row++) {
          const cell = sheet.getCell(row, column);
          if (cell.value === null || cell.value === '') continue;
          if (amount) {
            assert.equal(typeof cell.value, 'number');
            assert.equal(cell.numFmt, '#,##0.00');
            typedAmounts++;
          }
          if (date) {
            assert.ok(cell.value instanceof Date);
            assert.equal(cell.numFmt, 'yyyy-mm-dd');
            typedDates++;
          }
        }
      });
      assert.deepEqual([typedAmounts, typedDates], [amounts, dates], name);
      for (let row = 2; row <= sheet.rowCount; row++)
        ids.push(sheet.getCell(row, 1).text);
    }
    assert.equal(new Set(ids).size, 7);
    assert.deepEqual(ids.sort(), result.cases.map((c) => c.caseId).sort());
    const bridge = book.getWorksheet('Reconciliation Bridge')!;
    let formulas = 0;
    bridge.eachRow((row) =>
      row.eachCell((cell) => {
        if (cell.type === ExcelJS.ValueType.Formula) formulas++;
      }),
    );
    assert.ok(formulas > 0);
    for (const c of result.cases.filter((c) => c.bridgeEffect !== 0)) {
      const rows: ExcelJS.Row[] = [];
      bridge.eachRow((row) => {
        if (row.getCell(1).value === c.caseId) rows.push(row);
      });
      assert.equal(rows.length, 1);
      assert.equal(rows[0].getCell(5).value, c.bridgeEffect / 100);
      assert.ok(rows[0].getCell(6).text.length > 0);
    }
    if (extension === 'pdf') {
      assert.ok(book.getWorksheet('PDF Row Origins')!.rowCount > 13);
      const replay = await readFile(
        files[1].name,
        files[1].original!,
        files[1].pdf!.cuts,
      );
      assert.deepEqual(replay.sheets, files[1].sheets);
    }
    const saved = await saveSession({
      files,
      mappings,
      scope: result.scope,
      decisions: [],
      rejected: [],
      events: [],
      review,
    });
    const restored = await restoreSession(saved);
    assert.deepEqual(restored.result, result);
    assert.deepEqual(restored.mappings, mappings);
    files.forEach((file, side) =>
      assert.deepEqual(
        new Uint8Array(restored.files[side].original!),
        new Uint8Array(file.original!),
      ),
    );
    const changed = structuredClone(result);
    changed.ledger.transactions[0].amount++;
    await assert.rejects(
      exportWorkbook(changed, files, review),
      /النتيجة لا تطابق إعادة الحساب من المصدر/,
    );
  }
});
