// Generated by scripts/prepare-ocr-assets.mjs from pinned local packages.
export const VISUAL_ENGINE = Object.freeze({
  "library": "tesseract.js",
  "version": "7.0.0",
  "languages": "eng+ara",
  "assetHashes": {
    "worker-vendor.js": "576b7df7e3393e137e51849357c9adb53fe7ac1bb69bfa06cf3d61520f182c6d",
    "tesseract-core-lstm.wasm.js": "eef5f8b2f8e20e150680b20adaec4a60babafee3adbe8a94583c81fee46e8680",
    "eng.traineddata.gz": "45b4cb346724ac1774f1c36f42f182b887bcdb28ebe63e6fff90ac41f3fcff91",
    "ara.traineddata.gz": "f4746c44b02342dd5b3d4f0198000f47d7c49f1a229e63e0f436c0592dcd9639",
    "worker.js": "4faaf3bf0aabdd360f3a8a280f37050fa7307799d30cb9f4ab2dbd9807383f38"
  }
} as const);
